# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/reference/configuration-reference
version: 2.1

orbs:
  node: circleci/node@6.3.0

jobs:
  cypress-run:
    docker:
      - image: cimg/node:22.14
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run Cypress tests
          command: ./node_modules/.bin/cypress run
          environment:
            CLICKUP_TOKEN: $CLICKUP_TOKEN
            TEAM_ID: $TEAM_ID

workflows:
  test:
    jobs:
      - cypress-run
